### ISSUE TITLE
Automatic job renewal via scheduled pipelines

### ISSUE THREAD

**Issue by mishak87** [rolodato/gitlab-letsencrypt#40]
To automatically renew certificates you could use Scheduled CI pipelines

* [ ] Add master branch to protected branches if it is not there already
* [ ] Add **protected** [secret variable](https://gitlab.com/help/ci/variables/README#secret-variables) PRIVATE_TOKEN
* [ ] Add renew job to .gitlab-ci.yml
```yaml
stages:
  # ...
  - renew_ssl

renew_ssl:
  stage: renew_ssl
  script:
    - |
      if [ -z "${RENEW_SSL:-}" ]; then
        exit
      fi
      # TODO renew command
  only:
    - master
```
* [ ] Create pipeline schedule  
interval pattern: 1 month
target branch: master
variables:
  `RENEW_SSL` = `1`

I don't know if you can commit from CI job. If not using deployment key with allowed write access will be necessary.

**Comment by gabrielperales** [comment]
@mishak87 This info would be very appreciated if it were on the readme

**Comment by nathansmonk** [comment]
+1 for this. I tried to implement it, but because a scheduled pipeline needs to complete before the challenge pipeline it can't work at the moment.

**Comment by axilleas** [comment]
I did it in my project https://gitlab.com/axil/axil.gitlab.io/blob/master/.gitlab-ci.yml.

Example:

```yaml
letsencrypt:
  image: node:8-alpine
  stage: post-deploy
  variables:
    DOMAIN: "axilleas.me"
  before_script:
    - apk add git python --update-cache
    - npm install -g gitlab-letsencrypt --unsafe-perm
  script: |
    gitlab-le \
    --production \
    --domain $DOMAIN www.$DOMAIN \
    --email $LE_EMAIL \
    --token $LE_TOKEN \
    --repository $CI_PROJECT_URL \
    --path content/.well-known/acme-challenge
  only:
    - schedules
```
